routes/web.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'Website\PagesController@home']);

Route::get('/noticia/{id}', ['as' => 'news', 'uses' => 'Website\PagesController@news']);

Route::group(['prefix' => 'adm', 'as' => 'adm.'], function () {
    Route::get('/login', ['as' => 'login', 'uses' => 'Website\UsersController@login']);
    Route::post('/valida', ['as' => 'valida', 'uses' => 'Website\UsersController@valida']);

    Route::get('/conteudo', ['as' => 'conteudo', 'uses' => 'Website\AdminController@index']);
    Route::post('/conteudo', ['as' => 'conteudo', 'uses' => 'Website\AdminController@store']);

    Route::get('/conteudo/new', ['as' => 'new', 'uses' => 'Website\AdminController@create']);
    Route::get('/conteudo/edit/{id}', ['as' => 'edit', 'uses' => 'Website\AdminController@edit']);
    Route::post('/conteudo/{id}', ['as' => 'edit', 'uses' => 'Website\AdminController@update']);
    Route::get('/conteudo/delete/{id}', ['as' => 'delete', 'uses' => 'Website\AdminController@destroy']);
});

app/Models/Files.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Files extends Model
{
    //
}

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class News extends Model
{
    //
}

app/Models/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Website/AdminController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\News;

class AdminController extends Controller

{

    public function index()
    {
        $news = News::all();
        return view('website.admin.admin', compact('news'));
    }


    public function create()
    {
        $news = News::all();
        return view('website.admin.new', compact('news'));
    }

    public function store(Request $request)
    {
        $news = new News();
        $news->title = $request->input('tituloNoticia');
        $news->content_news = $request->input('conteudoNoticia');
        $news->save();
        return redirect('adm/conteudo');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $news = News::find($id);
        if (isset($news)){
            return view('website.admin.edit', compact('news'));
        }
        return redirect('adm/conteudo');
    }

    public function update(Request $request, $id)
    {
        $news = News::find($id);
        if (isset($news)){
            $news->title = $request->input('tituloNoticia');
            $news->content_news = $request->input('conteudoNoticia');
            $news->save();
        }
        return redirect('adm/conteudo');
    }

    public function destroy($id)
    {
        $news = News::find($id);
        if (isset($news)) {
            $news->delete();
        }
        return redirect('adm/conteudo');
    }
}

app/Http/Controllers/Website/PagesController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use App\Models\News;
use Illuminate\Support\Facades\Cache;

class PagesController extends Controller
{
    public function home(){
        $news = News::all();
        return view('website.page.home', compact('news'));
        // return view('website.page.home');
    }

    public function news($id){
        $news = News::find($id);
        
        if(isset($news)){  
        Cache::add($news, 'views');
        $news->views+=1;
        $news->save();
        return view('website.page.news', compact('news'));     
        }
        return redirect('/');
    }
}

app/Http/Controllers/Website/UsersController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UsersController extends Controller
{
    public function login(){
        return view('website.account.login');
    }

    public function valida(Request $request){

        $array = $request->all();
        
        $dados = DB::connection("projeto")
                ->table("users")
                ->select("*")
                ->where("email", $array['email'])
                ->get();
        
        if( $array['password'] == $dados[0]->password ){
            return redirect()->route('adm.conteudo');
        }else{
            return redirect()->route('adm.login');
        }
    }
}

resources/views/website/account/login.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,400,700,900&display=swap" rel="stylesheet">  
    <link rel="stylesheet" href="{{ asset('css/website.css') }}">
</head>
<body>   
    <div class="login-background">
        <div>
            <img src="{{asset('image/website/logo-login.svg')}}">
        </div>
        <div class="login-wrapper">
            <form action="valida" method="POST">
                <h1>Seja bem vindo</h1>
                <P>Acesso restrito ao colunista</P>
                
                <input 
                    class="mt-20 input" 
                    type="email"
                    name="email" 
                    placeholder="E-mail"
                    required>

                <input 
                    class="input" 
                    type="password" 
                    name="password" 
                    placeholder="Senha" 
                    required>

                <button class="input button-primary">Login</button>            
            </form>
        </div>
    </div>
    <script src="{{ mix('js/website.js') }}"></script>  
</body>
</html>

resources/views/website/admin/admin.blade.php
@extends('website.template.master')
@section('content')

@include('website.admin.dashboard')

<a class="btn btn-dark mb-2" href="{{route('adm.new')}}" role="button">Criar nova notícia</a>
<div class="row mt-2" style="min-height: 15rem">
    {{-- tabela --}}
    <div class="col-sm-12 text-center mb-2">
        <table class="table table-striped">
            <thead>
                <tr>
                <th scope="col" style="width: 10rem">#ID</th>
                <th scope="col">Título</th>
                <th scope="col" style="width: 15rem">Data da Publicação</th>
                <th scope="col" style="width: 10rem">Visualizações</th>
                <th scope="col-sm" style="width: 15rem">Ação</th>
                </tr>
            </thead>
            <tbody>
                
                @foreach ($news as $news)
                    <tr>
                        <th scope="row">{{$news->id}}</th>
                        <td>{{Str::limit($news->title, 30)}}</td>
                        <td>{{$news->created_at}}</td>
                        <td>{{$news->views}}</td>
                        <td>
                            <a class="btn btn-dark" href="/adm/conteudo/edit/{{$news->id}}" role="button">Editar</a>
                            <a class="btn btn-dark" href="/adm/conteudo/delete/{{$news->id}}" role="button">Excluir</a>
                        </td>
                    </tr>           
                @endforeach

            </tbody>
        </table>
    </div> 
</div>

@endsection

resources/views/website/admin/dashboard.blade.php
<div class="row">
    <div class="col-sm-6 mx-0 d-inline-flex">
        <div class="card border-dark mb-3 mt-5 p-3" style="width: 100%">
            <h5 class="card-title">Nome do Usuário</h5>
            <p class="card-text">Cargo do Usuário</p>
        </div>
    </div>
    <div class="col-sm-6 d-inline-flex text-center">
        <div class="card border-dark mb-3 mt-5 p-3">
            <p class="card-text">total de notícias publicadas</p>
            <h1 class="card-title " style="width: 15rem">{{$news->count()}}</H1>
        </div>
        <div class="card border-dark ml-2 mb-3 mt-5 p-3">
            <p class="card-text">total de visualizações</p>
            <H1 class="card-title" style="width: 15rem">{{$news->sum('views')}}</H1>
        </div>
    </div>
</div>

resources/views/website/admin/edit.blade.php
@extends('website.template.master')
@section('content')

@include('website.admin.dashboard')

<form action="/adm/conteudo/{{$news->id}}" method="POST">
    @csrf
    <div class="row">
        <div class="col-sm-4">
            <h2 class="mb-5">Editando notícia</h2>
            <h6>ID: {{$news->id}}</h6>
            <h6>Data de publicação: {{$news->created_at}}</h6>
            <h6>Visualizações: {{$news->views}}</h6>            
        </div>
        <div class="col-sm-8">
        <input class="input-group form-control mb-2" type="text" name="tituloNoticia" value="{{$news->title}}">
            <textarea class="form-control" rows="10" name="conteudoNoticia">{{$news->content_news}}</textarea>
            <button type="submit" class="btn btn-dark mt-2">Salvar</button>
            <a class="btn btn-dark mb-2 mt-3" href="{{route('adm.conteudo')}}" role="button">Sair</a>
        </div>
    </div>
</form>

@endsection

resources/views/website/admin/new.blade.php
@extends('website.template.master')
@section('content')

@include('website.admin.dashboard')

<form action="{{route('adm.conteudo')}}" method="POST">
    @csrf
    <div class="row">
        <div class="col-sm-12">
            <div>
                <h2 class="mb-3">Criando nova notícia</h2>      
            </div>
            <input class="input-group form-control mb-2" type="text" name="tituloNoticia"
                placeholder="Título da notícia">
            <textarea class="form-control" id="textArea" rows="10" name="conteudoNoticia"
                placeholder="Conteúdo da notícia"></textarea>
            <button type="submit" class="btn btn-dark mt-2">Salvar</button>
            <a class="btn btn-dark mb-2 mt-3" href="{{route('adm.conteudo')}}" role="button">Sair</a>
        </div>
    </div>
</form>

@endsection

resources/views/website/page/home.blade.php
@extends('website.template.master')
@section('content')

    <div class="container px-0">
        <img src="{{asset('/image/website/banner-principal.svg')}}" width="100%" alt="">            
    </div>
    
    <br>
    <h4>Todas as notícias</h4>
    <br>
    
    <div class="row" style="min-height: 10rem">
        @foreach ($news as $news)
        <div class="col-sm-4 mb-5">
            <div class="card">
                <img class="card-img-top" src="{{asset('/image/website/resimg.png')}}" alt="">
                <div class="card-body" style="height: 11rem">
                    <h5 class="card-title">{{Str::limit($news->title, 50)}}</h5>
                    <p class="card-text">{{Str::limit($news->content_news, 120)}}</p>
                </div>
                <a class="btn btn-dark m-3" href="/noticia/{{$news->id}}" role="button" style="max-width: 7rem">Ler mais...</a>
                <div class="card-footer">
                    <small class="text-muted">Postado em {{$news->created_at}}</small>
                </div>
            </div>
        </div>
        @endforeach
    </div>
@endsection

resources/views/website/page/news.blade.php
@extends('website.template.master')
@section('content')

    <div class="container px-0">
        <img src="{{asset('/image/website/banner-principal.svg')}}" width="100%" alt="">            
    </div>
    <div style="min-height: 10rem">
        <div class="row">
            <div class="col-sm-12 mt-4">
                <img class="rounded float-right mt-4 ml-4 mb-2 mr-0" src="{{asset('/image/website/resimg.png')}}" style="width: 30rem" alt="">
                <h1 class="mb-3">{{$news->title}}</h1>
                <p class="text-justify ">
                    {{$news->content_news}}
                </p>
            </div>
        </div>
    </div>
    
@endsection

resources/views/website/template/footer.blade.php
<footer class="mt-5">
    <div class="container">
        <img src="{{ asset('image/website/footer-detail.svg') }}" class="align-self-center" width="100%" alt="">
    </div>
    <div class="bg-dark">
        <div class="container mt-2">
            <div class="row">
                <div class="col-xl-2 mb-4 mt-5">
                    <p><a class="text-light" href="{{route('home')}}">Home</a></p>
                    <p><a class="text-light" href="#!">Sobre a VDP</a></p>
                    <p><a class="text-light" href="#!">Notícias</a></p>
                    <p><a class="text-light" href="#!">Contato</a></p>
                </div>
                <div class="col-xl-2 mb-4 mt-5">
                    <p><a class="text-light" href="{{route('adm.login')}}">Area do colunista</a></p>
                    <p><a class="text-light" href="#!">Perfil</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/website/template/header.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="collapse navbar-collapse container" id="navbarHeader">
        {{-- Logo --}}
        <img src="{{ asset('image/website/vdp.svg') }}" height="30"/>
        {{-- Navegação  --}}
        <ul class="ml-3 navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{{route('home')}}">Home</a></li>
            <li class="nav-item disabled"><a class="nav-link" href="#">Sobre</a></li>
            <li class="nav-item disabled"><a class="nav-link" href="#">Notícias</a></li>
            <li class="nav-item disabled"><a class="nav-link" href="#">Contato</a></li>
        </ul>
        {{-- Botão login --}}
        <a class="btn btn-outline-light badge badge-pill px-3 py-2" href="{{route('adm.login')}}" role="button">Entrar</a>
    </div>
</nav>

resources/views/website/template/master.blade.php
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>A Voz do Povo</title>
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,400,700,900&display=swap" rel="stylesheet">  
        <link rel="stylesheet" href="{{ asset('css/website.css') }}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>
        @include('website.template.header')
            <div class="container mt-5">
                @yield('content')
            </div>
        @include('website.template.footer')
        <script src="{{ mix('js/website.js') }}"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>